### ISSUE TITLE
Create step-by-step instructions for Flashing LED project !

### ISSUE THREAD

**Issue by RitikKumarParvat** [adrianyorke/raspberrypi-and-diy-projects#15]
step by step instruction for the flashing LED project is modified as you suggested once check it.

**Comment by adrianyorke** [comment]
Duplicate Issue

**Comment by RitikKumarParvat** [comment]
in what ?

**Comment by adrianyorke** [comment]
We already had an issue for this task #6 so this new issue #15 is a duplicate.

You have 1 issue per contribution and it's tracked against the pull request. I added a link from your PR to #6 before the merge so it automatically closes the issue.

Thanks for the contribution. Nice, clear presentation style. Hopefully will have many more 👍
