### ISSUE TITLE
Check links are valid in main README document

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/raspberrypi-and-diy-projects#3]
Implement github action (ci build) that checks all links are still valid in README document. Should be executed for each build.

Here's an example of a marketplace action that could provide this basic functionality:
https://github.com/marketplace/actions/check-links-with-linkcheck

**Comment by sdesani** [comment]
If its not already taken, can you assign this to me ?

**Comment by adrianyorke** [comment]
Hi, Sure, and thanks for the offer.

Please add your comment on the actual issue so I can assign it to you.

**Comment by sdesani** [comment]
Commenting here so it can be assigned!

**Comment by sdesani** [comment]
Created the PR - https://github.com/adrianyorke/raspberrypi-and-diy-projects/pull/9
