### ISSUE TITLE
Create contibuting guidelines to explain how to submit documentation additions and updates

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/raspberrypi-and-diy-projects#4]
It would be helpful to explain the contributing process and guide contributors so they can effectively submit their work.

Consider:

- Development and testing standards that should be followed
- Working on a fork repo
- Cloning repo
- Branch naming
- Pull request usage
- Recognition in Contributors section

**Comment by adrianyorke** [comment]
A good example can be found here:
https://github.com/adrianyorke/robotframework-cookbook/blob/master/CONTRIBUTING.md

**Comment by ayushsarode** [comment]
I want to work on it, Can you assign me?

**Comment by adrianyorke** [comment]
Welcome @ayushsarode and thanks for the offer. I've assigned this issue to you.

**Comment by ayushsarode** [comment]
Hey @adrianyorke 
"Should I include a 'Contributing' section in the README file or should I create a separate 'CONTRIBUTING.md' file?"

**Comment by adrianyorke** [comment]
A separate file in the root folder (same location as README) is the accepted convention. You can include a link to `CONTRIBUTING.md` in the README `Notes for contributors` section with text like "Contributions from the wider community are most welcome! Please follow the instructions (here)."
