### ISSUE TITLE
Create Code of Conduct for this project

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/raspberrypi-and-diy-projects#5]
Something similar to Contributor Covenant, version 1.4:
https://www.contributor-covenant.org/version/1/4/code-of-conduct/

Or the latest version 2.1:
https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Comment by Pariharx7** [comment]
Hey Adrian 
I'd like to work on this issue. 
Can you assign me the issue.

**Comment by adrianyorke** [comment]
Welcome Himanshu, and thanks for the offer.
