### ISSUE TITLE
Create step-by-step instructions for Flashing LED project

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/raspberrypi-and-diy-projects#6]
Create step-by-step instructions how to build a Flashing LED project using the GPIO pins available on most Raspberry Pi models.

A single document should be created using Markdown and uploaded here:
https://github.com/adrianyorke/raspberrypi-and-diy-projects/blob/master/docs/section_01/project_01_01.md

**Comment by ericmchen15** [comment]
Hi @adrianyorke Can I please be assigned to this task? thanks.

**Comment by adrianyorke** [comment]
Thanks for the kind offer @ericmchen15 - welcome!
